<a href="https://colab.research.google.com/github/ragulsulochana/Ragul-codeboosters-2026/blob/main/DAY%203/DAY_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install requests --quiet
import pandas as pd
import numpy as np
import requests
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

print("All libraries Installed and imported")

All libraries Installed and imported

In [4]:
raw_df = pd.read_csv("/content/messy_sales_data.csv")
print(f"Raw Data loaded:{raw_df.shape[0]} rows, {raw_df.shape[1]} columns")
print(raw_df.columns.tolist())
print("First 5 rows without index:")
print(raw_df.head(5).to_string(index=False))

Raw Data loaded:30 rows, 9 columns
['order_id', 'customer_name', 'product', 'category', 'quantity', 'unit_price', 'order_date', 'city', 'sales_rep']
First 5 rows without index:
 order_id customer_name  product    category  quantity  unit_price order_date      city   sales_rep
     1001  Ramesh Kumar   Laptop Electronics       2.0       45000 2024-01-05    Mumbai Anil Sharma
     1002    Priya Nair      NaN Electronics       1.0       15000 2024-01-07     Delhi  Sunita Rao
     1003    AMIT VERMA Keyboard Accessories       3.0        1200 2024-01-08 Bangalore Anil Sharma
     1004  Sunita Patel  Monitor Electronics       NaN       22000 2024-01-10   Chennai  Ravi Kumar
     1005  Ramesh Kumar   Laptop Electronics       2.0       45000 2024-01-05    Mumbai Anil Sharma

In [5]:
print("="*55)
print("            DATA QUALITY DIAGNOSIS REPORT")
print("="*55)

print("1. Missing Values per column")
print(raw_df.isnull().sum())

print("2. Duplocate rows")
print(raw_df[raw_df.duplicated()])

print("3. Data types")
print(raw_df.dtypes)

print("4. Unique  Categories", raw_df['category'].unique())
print("5. ")

=======================================================
            DATA QUALITY DIAGNOSIS REPORT
=======================================================
1. Missing Values per column
order_id         0
customer_name    2
product          1
category         1
quantity         3
unit_price       0
order_date       0
city             0
sales_rep        0
dtype: int64
2. Duplocate rows
Empty DataFrame
Columns: [order_id, customer_name, product, category, quantity, unit_price, order_date, city, sales_rep]
Index: []
3. Data types
order_id           int64
customer_name     object
product           object
category          object
quantity         float64
unit_price         int64
order_date        object
city              object
sales_rep         object
dtype: object
4. Unique  Categories ['Electronics' 'Accessories' nan]
5.

In [7]:
print("=== Unique category name ===")
print(raw_df['category'].unique())
print("")
print("=== Sample Customer name ===")
print(raw_df['customer_name'].dropna().unique()[8])
print("")
print("=== Order Date analysis ===")
print(raw_df['order_date'].unique()[6])

=== Unique category name ===
['Electronics' 'Accessories' nan]

=== Sample Customer name ===
Pooja Gupta

=== Order Date analysis ===
2024-01-13

In [10]:
print ('='* 55)
print('DATA QUATITY DIAGNOSIS REPORT')
print ('='* 55)

print('1. Missing Values per column')
print(raw_df.isnull().sum())

print('2. Duplicate rows')
print(raw_df[raw_df.duplicated()])

print('3. Data types')
print(raw_df.dtypes)

print('\n[4. Unique categories]')
print(raw_df['category'].unique())
print('\n[5. Sample customer name]')

=======================================================
DATA QUATITY DIAGNOSIS REPORT
=======================================================
1. Missing Values per column
order_id         0
customer_name    2
product          1
category         1
quantity         3
unit_price       0
order_date       0
city             0
sales_rep        0
dtype: int64
2. Duplicate rows
Empty DataFrame
Columns: [order_id, customer_name, product, category, quantity, unit_price, order_date, city, sales_rep]
Index: []
3. Data types
order_id           int64
customer_name     object
product           object
category          object
quantity         float64
unit_price         int64
order_date        object
city              object
sales_rep         object
dtype: object

[4. Unique categories]
['Electronics' 'Accessories' nan]

[5. Sample customer name]

In [11]:
df = raw_df.copy()
print(f'working copy created: (df.shape)')
print('raw_df is untouched - we can always reset ')

working copy created: (df.shape)
raw_df is untouched - we can always reset

In [12]:
#FIX 1

print("Before fixing nulls:", df.isnull().sum().sum())

df['customer_name'].fillna("No Name", inplace=True)
median_quantity = df['quantity'].median()
df['quantity'].fillna(median_quantity, inplace=True)
print("Filled missing values in the qnantity with median", median_quantity)

df['category'].fillna("No Category", inplace=True)

df['product'].fillna("No Product", inplace=True)
print("After fixing nulls:", df.isnull().sum().sum())

Before fixing nulls: 7
Filled missing values in the qnantity with median 2.0
After fixing nulls: 0

In [13]:
df

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma
1,1002,Priya Nair,No Product,Electronics,1.0,15000,2024-01-07,Delhi,Sunita Rao
2,1003,AMIT VERMA,Keyboard,Accessories,3.0,1200,2024-01-08,Bangalore,Anil Sharma
3,1004,Sunita Patel,Monitor,Electronics,2.0,22000,2024-01-10,Chennai,Ravi Kumar
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma
5,1006,kiran mehta,Mouse,Accessories,10.0,800,07-01-2024,Pune,Sunita Rao
6,1007,Deepak Singh,Headphones,Electronics,2.0,3500,2024-01-12,Hyderabad,Ravi Kumar
7,1008,No Name,Webcam,Accessories,1.0,2500,2024-01-13,Mumbai,Anil Sharma
8,1009,Ananya Das,Laptop,Electronics,1.0,45000,2024-01-15,Kolkata,Sunita Rao
9,1010,Vikram Iyer,Keyboard,Accessories,5.0,1200,2024-01-15,Chennai,Ravi Kumar
10,1011,Pooja Gupta,Monitor,Electronics,2.0,22000,2024-01-18,Delhi,Anil Sharma
11,1012,SURESH RAO,USB Hub,Accessories,8.0,600,2024-01-20,Bangalore,Sunita Rao
12,1013,Meera Joshi,Laptop,Electronics,2.0,45000,2024-01-22,Pune,Ravi Kumar
13,1014,Arjun Nair,Headphones,Electronics,3.0,3500,21-01-2024,Kochi,Anil Sharma
14,1015,Tanvi Mehta,Webcam,Accessories,2.0,2500,2024-01-25,Surat,Sunita Rao
15,1016,Kiran Mehta,Mouse,Accessories,10.0,800,2024-01-07,Pune,Sunita Rao
16,1017,Deepak Singh,Keyboard,Accessories,5.0,1200,2024-01-28,Hyderabad,Ravi Kumar
17,1018,Rohit Verma,Monitor,Electronics,1.0,22000,2024-01-30,Delhi,Anil Sharma
18,1019,Sneha Reddy,Laptop,Electronics,1.0,45000,2024-02-01,Hyderabad,Ravi Kumar
19,1020,Gaurav Shukla,USB Hub,Accessories,15.0,600,2024-02-03,Lucknow,Sunita Rao
20,1021,Nisha Kapoor,Headphones,Electronics,2.0,3500,2024-02-05,Chandigarh,Anil Sharma
21,1022,Ajay Tiwari,Webcam,Accessories,3.0,2500,2024-02-07,Bhopal,Ravi Kumar
22,1023,ANANYA DAS,Laptop,Electronics,1.0,45000,2024-01-15,Kolkata,Sunita Rao
23,1024,Preeti Saxena,Keyboard,Electronics,4.0,1200,2024-02-10,Kanpur,Anil Sharma
24,1025,Amit Bose,Mouse,Accessories,6.0,800,2024-02-12,Kolkata,Sunita Rao
25,1026,No Name,Headphones,Electronics,1.0,3500,2024-02-14,Mumbai,Ravi Kumar
26,1027,Rekha Nair,Monitor,No Category,2.0,22000,2024-02-15,Kochi,Anil Sharma
27,1028,Harish Pillai,Laptop,Electronics,3.0,45000,2024-02-18,Thiruvananthapuram,Ravi Kumar
28,1029,Sanjay Dubey,USB Hub,Accessories,10.0,600,2024-02-20,Allahabad,Sunita Rao
29,1030,Kavya Nambiar,Webcam,Accessories,2.0,2500,2024-02-22,Thrissur,Anil Sharma

In [14]:
raw_df

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma
1,1002,Priya Nair,NaN,Electronics,1.0,15000,2024-01-07,Delhi,Sunita Rao
2,1003,AMIT VERMA,Keyboard,Accessories,3.0,1200,2024-01-08,Bangalore,Anil Sharma
3,1004,Sunita Patel,Monitor,Electronics,NaN,22000,2024-01-10,Chennai,Ravi Kumar
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma
5,1006,kiran mehta,Mouse,Accessories,10.0,800,07-01-2024,Pune,Sunita Rao
6,1007,Deepak Singh,Headphones,Electronics,2.0,3500,2024-01-12,Hyderabad,Ravi Kumar
7,1008,NaN,Webcam,Accessories,1.0,2500,2024-01-13,Mumbai,Anil Sharma
8,1009,Ananya Das,Laptop,Electronics,1.0,45000,2024-01-15,Kolkata,Sunita Rao
9,1010,Vikram Iyer,Keyboard,Accessories,5.0,1200,2024-01-15,Chennai,Ravi Kumar
10,1011,Pooja Gupta,Monitor,Electronics,2.0,22000,2024-01-18,Delhi,Anil Sharma
11,1012,SURESH RAO,USB Hub,Accessories,8.0,600,2024-01-20,Bangalore,Sunita Rao
12,1013,Meera Joshi,Laptop,Electronics,NaN,45000,2024-01-22,Pune,Ravi Kumar
13,1014,Arjun Nair,Headphones,Electronics,3.0,3500,21-01-2024,Kochi,Anil Sharma
14,1015,Tanvi Mehta,Webcam,Accessories,2.0,2500,2024-01-25,Surat,Sunita Rao
15,1016,Kiran Mehta,Mouse,Accessories,10.0,800,2024-01-07,Pune,Sunita Rao
16,1017,Deepak Singh,Keyboard,Accessories,5.0,1200,2024-01-28,Hyderabad,Ravi Kumar
17,1018,Rohit Verma,Monitor,Electronics,1.0,22000,2024-01-30,Delhi,Anil Sharma
18,1019,Sneha Reddy,Laptop,Electronics,1.0,45000,2024-02-01,Hyderabad,Ravi Kumar
19,1020,Gaurav Shukla,USB Hub,Accessories,15.0,600,2024-02-03,Lucknow,Sunita Rao
20,1021,Nisha Kapoor,Headphones,Electronics,2.0,3500,2024-02-05,Chandigarh,Anil Sharma
21,1022,Ajay Tiwari,Webcam,Accessories,3.0,2500,2024-02-07,Bhopal,Ravi Kumar
22,1023,ANANYA DAS,Laptop,Electronics,1.0,45000,2024-01-15,Kolkata,Sunita Rao
23,1024,Preeti Saxena,Keyboard,Electronics,4.0,1200,2024-02-10,Kanpur,Anil Sharma
24,1025,Amit Bose,Mouse,Accessories,6.0,800,2024-02-12,Kolkata,Sunita Rao
25,1026,NaN,Headphones,Electronics,1.0,3500,2024-02-14,Mumbai,Ravi Kumar
26,1027,Rekha Nair,Monitor,NaN,2.0,22000,2024-02-15,Kochi,Anil Sharma
27,1028,Harish Pillai,Laptop,Electronics,3.0,45000,2024-02-18,Thiruvananthapuram,Ravi Kumar
28,1029,Sanjay Dubey,USB Hub,Accessories,10.0,600,2024-02-20,Allahabad,Sunita Rao
29,1030,Kavya Nambiar,Webcam,Accessories,NaN,2500,2024-02-22,Thrissur,Anil Sharma

In [15]:
#FIX 2 REMOVING DUPLICATE VALUES

print("Before Duplication: ", len(df))
print("Duplicate rows: ", df.duplicated().sum())
print("\nDuplicate rows:")
print(df[df.duplicated(keep=False)][['order_id', 'customer_name', 'product', 'category', 'quantity', 'unit_price', 'order_date', 'city', 'sales_rep']])

df.drop_duplicates(inplace=True)

print("\nAfter duplication:", )

Before Duplication:  30
Duplicate rows:  0

Duplicate rows:
Empty DataFrame
Columns: [order_id, customer_name, product, category, quantity, unit_price, order_date, city, sales_rep]
Index: []

After duplication:

In [17]:
print("Sample dates before parsing: ")
print(df['order_date'].head(5).tolist())

df['order_date'] = pd.to_datetime(
    df['order_date'],
    dayfirst=False,
    errors='coerce'
)
nat_count = df['order_date'].isnull().sum()
print(f"\nUnparseable dates (NaT): {nat_count}")

# Fixed: removed parentheses from .year and .month
df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month
df['month_name'] = df['order_date'].dt.strftime('%B')

print('\nSample Date after parsing:')
print(df[['order_date', 'year', 'month', 'month_name']].head(5))

Sample dates before parsing:
['2024-01-05', '2024-01-07', '2024-01-08', '2024-01-10', '2024-01-05']

Unparseable dates (NaT): 2

Sample Date after parsing:
  order_date    year  month month_name
0 2024-01-05  2024.0    1.0    January
1 2024-01-07  2024.0    1.0    January
2 2024-01-08  2024.0    1.0    January
3 2024-01-10  2024.0    1.0    January
4 2024-01-05  2024.0    1.0    January