<a href="https://colab.research.google.com/github/ragulsulochana/Ragul-codeboosters-2026/blob/main/DAY%202/day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

print("all libraries imported successfully")
print (f"pandas version:{pd.__version__}")
print(f"sqlite3 version:{sqlite3.sqlite_version}")

all libraries imported successfully
pandas version:2.2.2
sqlite3 version:3.37.2

In [8]:
df = pd.read_csv("/content/student_performance.csv")
print(f"Dataset Loaded: {df.shape}")
print("Columns: ",df.columns.tolist())
print("\nFirst Three rows:")
df.head(3)

Dataset Loaded: (30, 13)
Columns:  ['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

First Three rows:

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023

In [9]:
conn = sqlite3.connect('college.db')

cursor = conn.cursor()
print("Database created and Successfully Connected to SQLite")

Database created and Successfully Connected to SQLite

In [ ]:
df.to_sql(
    'students',
    conn,
    if_exists='replace',
    index=False
)

cursor.execute("SELECT COUNT(*) FROM students;")
count = cursor.fetchone()[0]
print(f"Number of rows in the 'students' table: {count}")

Number of rows in the 'students' table: 30

In [10]:
def run_query(query, description):
  print(description)
  result = pd.read_sql_query(query, conn)
  return result

In [11]:
query1 = """
  SELECT student_id, name, department, math_score, attendance_percentage
  FROM students
  LIMIT 10
"""

result1 = run_query(query1, "Query 1: First 10 Students (SELECT + LIMIT)")
result1

Query 1: First 10 Students (SELECT + LIMIT)

,student_id,name,department,math_score,attendance_percentage
0,1001,Aarav Sharma,Computer Science,85,92
1,1002,Priya Patel,Computer Science,76,87
2,1003,Rohit Verma,Electronics,65,78
3,1004,Sneha Reddy,Mechanical,70,95
4,1005,Arjun Nair,Computer Science,92,90
5,1006,Meera Joshi,Electronics,58,72
6,1007,Kiran Kumar,Civil,73,85
7,1008,Divya Singh,Computer Science,88,96
8,1009,Rahul Mishra,Mechanical,62,68
9,1010,Ananya Das,Computer Science,95,98

In [14]:
conn = sqlite3.connect('college.db')
cursor = conn.cursor()

query = "SELECT student_id , name , age FROM students LIMIT 10"
data = pd.read_sql(query,conn)
print("=== DataBase Connected Successfully ===")
print(data)
conn.close()

=== DataBase Connected Successfully ===
   student_id          name  age
0        1001  Aarav Sharma   19
1        1002   Priya Patel   20
2        1003   Rohit Verma   19
3        1004   Sneha Reddy   20
4        1005    Arjun Nair   19
5        1006   Meera Joshi   20
6        1007   Kiran Kumar   21
7        1008   Divya Singh   19
8        1009  Rahul Mishra   20
9        1010    Ananya Das   19

In [18]:
conn = sqlite3.connect('college.db')
query = "SELECT name, department, math_score FROM students ORDER BY math_score DESC LIMIT 5"
data_top_5 = pd.read_sql(query, conn)
print("=== Top 5 Students by Math Score ===")
print(data_top_5)
conn.close()

=== Top 5 Students by Math Score ===
             name        department  math_score
0      Ananya Das  Computer Science          95
1     Tanvi Mehta  Computer Science          93
2      Arjun Nair  Computer Science          92
3  Akanksha Yadav  Computer Science          91
4  Swati Kulkarni  Computer Science          90

In [20]:
conn = sqlite3.connect('college.db')
query = "SELECT name, department, math_score, science_score, programming_score, attendance_percentage FROM students WHERE department = 'Computer Science'"
data = pd.read_sql(query, conn)
print("=== DataBase Connected Successfully ===")
print(data)
conn.close()

=== DataBase Connected Successfully ===
              name        department  math_score  science_score  \
0     Aarav Sharma  Computer Science          85             78
1      Priya Patel  Computer Science          76             82
2       Arjun Nair  Computer Science          92             88
3      Divya Singh  Computer Science          88             91
4       Ananya Das  Computer Science          95             89
5       Suresh Rao  Computer Science          83             86
6      Ajay Tiwari  Computer Science          71             69
7   Swati Kulkarni  Computer Science          90             87
8     Nisha Kapoor  Computer Science          79             84
9      Tanvi Mehta  Computer Science          93             90
10       Amit Bose  Computer Science          86             82
11   Gaurav Shukla  Computer Science          84             79
12  Akanksha Yadav  Computer Science          91             93

    programming_score  attendance_percentage
0                  91                     92
1                  79                     87
2                  95                     90
3                  93                     96
4                  97                     98
5                  88                     88
6                  76                     75
7                  92                     94
8                  83                     89
9                  96                     97
10                 89                     91
11                 87                     87
12                 94                     95

In [22]:
query5 = """
  SELECT name, department, attendance_percentage
  FROM students
  WHERE attendance_percentage > 90 AND department != 'Civil'
  ORDER BY attendance_percentage DESC
"""

result5 = run_query(query5, "Query 5: High Attendance (>90%) Excluding Civil")
result5

Query 5: High Attendance (>90%) Excluding Civil
             name        department  attendance_percentage
0      Ananya Das  Computer Science                     98
1     Tanvi Mehta  Computer Science                     97
2     Divya Singh  Computer Science                     96
3     Sneha Reddy        Mechanical                     95
4  Akanksha Yadav  Computer Science                     95
5  Swati Kulkarni  Computer Science                     94
6    Ritu Agarwal       Electronics                     93
7    Aarav Sharma  Computer Science                     92
8   Kavya Nambiar        Mechanical                     91
9       Amit Bose  Computer Science                     91

In [26]:
import sqlite3

conn = sqlite3.connect('college.db')
query5 = """
  SELECT name, department, attendance_percentage
  FROM students
  WHERE attendance_percentage > 93 AND department != 'Mechanical'
  ORDER BY attendance_percentage DESC
"""

result5 = run_query(query5, "Query 5: High Attendance (>93%) Excluding Mechanical")
conn.close()
result5

Query 5: High Attendance (>93%) Excluding Mechanical

             name        department  attendance_percentage
0      Ananya Das  Computer Science                     98
1     Tanvi Mehta  Computer Science                     97
2     Divya Singh  Computer Science                     96
3  Akanksha Yadav  Computer Science                     95
4  Swati Kulkarni  Computer Science                     94

In [32]:
import sqlite3

conn = sqlite3.connect('college.db')
query = """
  SELECT name
  FROM students
  WHERE name BETWEEN 'A' AND 'F'
  ORDER BY name
"""

result = run_query(query, "Query: Names starting with A-F using BETWEEN")
conn.close()
print(result)

Query: Names starting with A-F using BETWEEN
             name
0    Aarav Sharma
1     Ajay Tiwari
2  Akanksha Yadav
3       Amit Bose
4      Ananya Das
5      Arjun Nair
6  Deepak Chauhan
7     Divya Singh